baseURL = "SiddhiSDoshi.github.io/Website"
title = "Siddhi Doshi"
paginate = 20
theme = "PaperMod"
enableInlineShortcodes = true
enableRobotsTXT = true

[social]
twitter = "SiddhisDoshi"

[taxonomies]
tag = "tags"

[[menu.main]]
name = "Research"
url = "/research/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv.pdf"
weight = 2

[[menu.main]]
name = "Resources"
url = "https://automatic-router-3aa.notion.site/b04ae66c128743d4a9c5a17b1d653584?v=c3bdacae975a429aa84152ccc790390e&pvs=4"
weight = 3


[params]
description = "I am a PhD student in Economics and Public Policy at Tufts University. My research covers energy and environmental economics."
author = "Siddhi Doshi"
DateFormat = "January 2006"
defaultTheme = "light"
hideFooter = true
disableThemeToggle = true
ShowShareButtons = false
ShowReadingTime = false
disableSpecial1stPost = true
disableAnchoredHeadings = true
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = false
ShowToc = false
disableScrollToTop = true
TocOpen = true
ShowWordCount = false
UseHugoToc = true
comments = false
math = true
googleAnalytics = "G-GLJ57714DT"

  [params.profileMode]
  enabled = true
  title = "Siddhi Doshi"
  subtitle = "I am a PhD student in Economics and Public Policy at Tufts University. I study energy and environmental economics, particularly in developing countries. **I am on the 2025/26 academic job market**. My work and interests include the effects of renewable energy on electricity markets and policy designs that improve energy access. In my job market paper, I study how solar and nonsolar generation interact in the Indian power grid, and its implications for electricity reliability. Before starting graduate school, I worked on environmental regulation and economic growth as a research assistant at the Brookings Institution."
  imageUrl = "profile3.jpg"
  imageWidth = 240
  imageHeight = 240
  imageTitle = "Siddhi Doshi"

[[params.profileMode.buttons]]
    name = "Job Market Paper"
    url = "/papers/Siddhi_Doshi_JMP.pdf"

[[params.profileMode.buttons]]
    name = "CV"
    url = "cv.pdf"


  [[params.socialIcons]]
  name = "Email"
  url = "mailto:siddhi.doshi@tufts.edu"

  [[params.socialIcons]]
  name = "Google Scholar"
  url = "https://scholar.google.com/citations?user=m03icisAAAAJ&hl=en"


 [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/siddhisdoshi/"

 [[params.socialIcons]]
  name = "GitHub"
  url = "https://github.com/SiddhiSDoshi"

  [params.assets]
  disableHLJS = true
  disableScrollBarStyle = true

  [params.cover]
  hiddenInList = true
  hiddenInSingle = true

  [params.label]
  text = "Siddhi Doshi"
  icon = "favicon.ico"
  iconHeight = 18

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
guessSyntax = true
style = "xcode"

[markup.tableOfContents]
endLevel = 2
ordered = false
startLevel = 2
